version: 2.1

jobs:
  build_lineage:
    docker:
      - image: cimg/android:2023.10
    resource_class: large
    steps:
      - checkout
      - run:
          name: Setup Environment and Sync
          command: |
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            export PATH="$HOME/bin:$PATH"
            mkdir android && cd android
            repo init -u https://github.com/LineageOS/android.git -b lineage-18.1 --git-lfs
            repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: Compile Android Image
          no_output_timeout: 60m
          command: |
            export PATH="$HOME/bin:$PATH"
            export USE_CCACHE=1
            cd android
            rm -rf .repo
            source build/envsetup.sh
            lunch lineage_a9y18qlte-userdebug
            mka bacon -j$(nproc --all)
      - store_artifacts:
          path: android/out/target/product/a9y18qlte/
          destination: lineage_build_output

workflows:
  build_and_deploy:
    jobs:
      - build_lineage
